# Generated by Django 2.2.7 on 2019-12-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpayment',
            name='method',
        ),
    ]
