# Generated by Django 2.2.7 on 2019-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_productpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
