# Generated by Django 2.2.7 on 2019-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_productpayment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete'), ('F', 'Failed')], max_length=1),
        ),
    ]
