# Generated by Django 2.2.7 on 2019-12-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20191206_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
