# Generated by Django 2.2.7 on 2019-12-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_productpayment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpayment',
            name='user',
        ),
    ]
