# Generated by Django 2.2.7 on 2020-03-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='cvv',
            new_name='cvc',
        ),
    ]
