# Generated by Django 2.2.7 on 2019-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='activation_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
