# Generated by Django 2.2.7 on 2019-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_primary_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
