# Generated by Django 2.2.7 on 2019-12-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_platform_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='platform_charges',
            new_name='platform_fees',
        ),
    ]
