# Generated by Django 2.2.7 on 2019-12-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/avatar.png', upload_to='profiles'),
        ),
    ]
