# Generated by Django 2.2.7 on 2020-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191219_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
