# Generated by Django 2.2.7 on 2019-12-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PC', 'Platform Charges')], default='PC', max_length=2, unique=True)),
                ('data', models.TextField()),
                ('data_type', models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('F', 'Float'), ('B', 'Boolean')], max_length=1)),
            ],
        ),
    ]
