# Generated by Django 2.2.7 on 2020-03-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quote', models.TextField()),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StripeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PF', 'Platform Stripe Fees'), ('AT', 'Google Analytics Access Token'), ('RT', 'Google Analytics Refresh Token'), ('AC', 'Google Analytics Access Code'), ('RU', 'Google Analytics Redirect uri'), ('CI', 'Google Analytics Client ID'), ('CS', 'Google Analytics Client Secret'), ('SJ', 'Google Analytics Secret JSON'), ('VI', 'Google Analytics View ID')], default='PF', max_length=2, unique=True)),
                ('data', models.TextField()),
                ('data_type', models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('F', 'Float'), ('B', 'Boolean'), ('J', 'JSON')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_url', models.CharField(blank=True, max_length=200, null=True)),
                ('submenu_url', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('A', 'Artist'), ('C', 'Collector'), ('SA', 'Admin')], default='A', max_length=2)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Menu')),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='settings.Menu')),
            ],
            options={
                'ordering': ['menu'],
            },
        ),
    ]
