# Generated by Django 2.2.7 on 2019-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesetting',
            name='data_type',
            field=models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('F', 'Float'), ('B', 'Boolean'), ('J', 'JSON')], max_length=1),
        ),
    ]
