# Generated by Django 2.2.7 on 2019-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20191205_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesetting',
            name='name',
            field=models.CharField(choices=[('PF', 'Platform Stripe Fees')], default='PF', max_length=2, unique=True),
        ),
    ]
