# Generated by Django 2.2.7 on 2019-12-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20191210_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settings.Menu'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='submenu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='settings.Menu'),
        ),
    ]
