# Generated by Django 2.2.7 on 2019-12-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20191210_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='for_admin',
            field=models.BooleanField(default=True, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='for_artist',
            field=models.BooleanField(default=False, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='for_collector',
            field=models.BooleanField(default=False, verbose_name='Collector'),
        ),
    ]
