# Generated by Django 2.2.7 on 2019-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20191210_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenu',
            name='for_admin',
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='for_artist',
        ),
        migrations.RemoveField(
            model_name='usermenu',
            name='for_collector',
        ),
        migrations.AddField(
            model_name='usermenu',
            name='menu_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermenu',
            name='role',
            field=models.CharField(choices=[('A', 'Artist'), ('C', 'Collector'), ('SA', 'Admin')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='usermenu',
            name='submenu_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
