# Generated by Django 2.2.7 on 2019-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20191212_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenu',
            name='icon',
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
