# Generated by Django 2.2.7 on 2019-12-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20191212_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Menu'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='settings.Menu'),
        ),
    ]
