# Generated by Django 2.2.7 on 2019-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_auto_20191212_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='role',
            field=models.CharField(choices=[('A', 'Artist'), ('C', 'Collector'), ('SA', 'Admin')], default='A', max_length=2),
        ),
    ]
