# Generated by Django 2.2.7 on 2019-12-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20191213_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quote', models.TextField()),
                ('default', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
