# Generated by Django 2.2.7 on 2019-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesetting',
            name='name',
            field=models.CharField(choices=[('PF', 'Platform Stripe Fees'), ('AT', 'Google Analytics Access Token'), ('RT', 'Google Analytics Refresh Token'), ('AC', 'Google Analytics Access Code'), ('RU', 'Google Analytics Redirect uri'), ('CI', 'Google Analytics Client ID'), ('CS', 'Google Analytics Client Secret')], default='PF', max_length=2, unique=True),
        ),
    ]
