# Generated by Django 2.2.7 on 2019-12-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20191204_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='{}'),
        ),
    ]
