# Generated by Django 2.2.7 on 2019-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('I', 'Incomplete'), ('F', 'Failed')], default='I', max_length=1),
        ),
    ]
