# Generated by Django 2.2.7 on 2019-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0006_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='sav@swagytoon.com', max_length=254),
            preserve_default=False,
        ),
    ]
