# Generated by Django 2.2.7 on 2019-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_auto_20191210_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='arts.Tag'),
        ),
    ]
