# Generated by Django 2.2.7 on 2019-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0010_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
