# Generated by Django 2.2.7 on 2019-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0011_order_transaction_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_fees',
            field=models.IntegerField(default=0),
        ),
    ]
